version: '2.4'
services:
  baabp-an_main:
    container_name: baabp-an_main
    build: .
    image: baabp/ad:torch-cuda
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
#    command: nvidia-smi
    tty: true
    command: /bin/bash
    volumes:
      - .:/src
    ports:
      - "8008:8008"
      - "6006:6006"
      - "6007:6007"